(load "math.lisp")

(defun get-file-contents (filename)
  (with-open-file (stream filename)
    (let ((contents (make-string (file-length stream))))
      (read-sequence contents stream)
      contents)))

(defmacro input-filename (num) (concatenate 'string "inputs/input" (write-to-string num) ".txt"))
(defmacro fetch-input-string (num) `(get-file-contents ,`(input-filename ,num)))

(defparameter problem_solutions  #(

'((math::sum-mults-of-args-up-to 1000 3 5)
"Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.")

'((math::even-fibonacci-sum 4000000)
"Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
")

'((math::largest-prime-factor 600851475143)
"Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
")

'((math::max-palindrome-prod-of-2-n-digit-nums 3)
"Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
")

'((math::smallest-divisible-by-all-in-range 20)
"Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
")

'((math::square-of-sum-sum-of-square-diff 100)
"Problem 6
The sum of the squares of the first ten natural numbers is,
1^2 + 2^2 + ... + 10^2 = 385

The square of the sum of the first ten natural numbers is,
(1 + 2 + ... + 10)^2 = 55^2 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
")

'((math::nth-prime 10001)
"Problem 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10 001st prime number?
")

'((math::largest-n-digit-product-in-series 13 (fetch-input-string 8))
"Problem 8
The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

(Number in input file 8)

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
")

'((apply '* (math::pythagorean-triplets-with-sum-n 1000))
"Problem 9
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a^2 + b^2 = c^2

For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
")

'((reduce '+ (math::prime-list-range-by-division 2000000))
"Problem 10
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
Find the sum of all the primes below two million.
")))

(defun euler_fun (num &key solution show-form show-doc)
    "Takes problem number and evaluates the answer or shows solution form, according to keys.
    Numbering of problems starts with 1."
    (setf solution t) ;; It is the default action anyway, if all else is nil it should be executed, keyword allows for code clarity
    (if (or (< num 1) (> num (length problem_solutions)))
        (format t "Invalid problem number~%")
        (let ((problem-info (eval (aref problem_solutions (- num 1)))))
        (cond
            (show-form (first problem-info))
            (show-doc (second problem-info))
            (solution (eval (first problem-info)))))))

(defun show_solved (&key export)
"Prints the presentations and found solutions of all the problems on terminal,or exports them to solved_problems.txt"
(let ((dest (if export (open "solved_problems.txt" :direction :output :if-exists :overwrite :if-does-not-exist :create) t)))
        (loop for i from 1 to (length problem_solutions) do (format dest "****************************************~%~%~a~%~%Solution: ~a~%~%****************************************~%" 
                                (euler_fun i :show-doc t) (euler_fun i :solution t)))
(if export (close dest))
))